# version: "3.3"
# services:
#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "5000:5000"
#     environment:
#       DATABASE_URL: "postgres://postgres:password@db:5432/todoapp"
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     volumes:
#       - db-data:/var/lib/postgresql/data
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: todoapp

# volumes:
#   db-data:



version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Montez un fichier Nginx personnalisé

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/todoapp"
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp

volumes:
  db-data:
