apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    -- Votre script SQL d'initialisation ici
    CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    description TEXT NOT NULL
    );

