apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-db
  template:
    metadata:
      labels:
        app: todoapp-db
    spec:
      containers:
        - name: todoapp-db
          image: robertolandry/todoappdb:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: todoapp
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
        - name: init-script
          configMap:
            name: db-init-script



apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

