on: 
  push:
    branches: [main]

jobs:
  tag-build-and-push-image:
    runs-on: ubuntu-latest

    steps: 
      - name: clone the code 
        uses:  actions/checkout@v3
    
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and tag frontend image 
        run:  docker build -t robertolandry/todoappfrontend -f ./schedule-management-app/frontend/Dockerfile ./schedule-management-app/frontend
      - name: build and tag backend image  
        run:  docker build -t robertolandry/todoappbackend  -f ./schedule-management-app/backend/Dockerfile ./schedule-management-app/backend
      - name: build and tag db image  
              run:  docker build -t robertolandry/todoappdb -f ./schedule-management-app/db/Dockerfile ./schedule-management-app/db

      # - name: tag db
      #   run: |
      #       docker pull postgres:15
      #       docker tag  postgres:15 robertolandry/todoappdb:latest 

      - name: push all images on dockerhub 
        run: |
            docker push robertolandry/todoappfrontend:latest
            docker push robertolandry/todoappbackend:latest
            docker push robertolandry/todoappdb:latest 